<Solution xmlns:i="http://www.w3.org/2001/XMLSchema-instance" z:Id="i1" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/" xmlns="http://schemas.datacontract.org/2004/07/NationalInstruments.PackageBuilder.Engine">
    <Name>Volta Control Suite</Name>
    <SourceItems>
        <SourceItem z:Id="i2">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\ACIR_EIS.lvclass</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i3">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\ACIR_EIS_Create.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i4">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\Destroy.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i5">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\EIS Mode.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i6">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\EIS Parameters.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i7">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\Generate Plots.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i8">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\private\Decimate Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i9">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\private\Generate EIS Plots.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i10">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\private\Generate Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i11">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\protected\ObjectAttributes.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i12">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\protected\Process.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i13">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\protected\Process.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i14">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\protected\ProcessRepository.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i15">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\protected\StartProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i16">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\protected\StopProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i17">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\Start Stop Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i18">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\utils\ACIR_EIS_GetAttributes.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i19">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\utils\ACIR_EIS_New.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i20">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Battery.lvclass</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i21">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Battery_Create.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i22">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Battery_Destroy.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i23">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i24">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Get Chemistries.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i25">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Get Models.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i26">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Get SOC OCV Curve.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i27">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Load Model.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i28">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Load Simulation.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i29">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Model Parameters.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i30">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\private\Test PyBaMM Wrapper.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i31">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\protected\Charge Model.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i32">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\protected\Default Discharge Model.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i33">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\protected\ObjectAttributes.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i34">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\protected\Process.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i35">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\protected\Process.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i36">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\protected\ProcessRepository.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i37">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\protected\StartProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i38">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\protected\StopProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i39">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Reset Simulation.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i40">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Simulation Parameters.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i41">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\Step Simulation.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i42">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\utils\Battery_GetAttributes.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i43">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\utils\Battery_New.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i44">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\DCIR_HPPC.lvclass</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i45">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\DCIR_HPPC_Create.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i46">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\Destroy.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i47">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\Generate Plots.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i48">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\HPPC Mode.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i49">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\HPPC Parameters.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i50">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\private\Decimate Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i51">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\private\Generate DCIR Plots.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i52">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\private\Generate Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i53">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\protected\ObjectAttributes.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i54">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\protected\Process.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i55">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\protected\Process.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i56">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\protected\ProcessRepository.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i57">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\protected\StartProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i58">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\protected\StopProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i59">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\Start Stop Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i60">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\utils\DCIR_HPPC_GetAttributes.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i61">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\utils\DCIR_HPPC_New.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i62">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\Destroy.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i63">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\Erase Chart.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i64">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\Get Timestamp.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i65">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\Grapher.lvclass</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i66">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\Grapher_Create.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i67">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\private\Get Measurements.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i68">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\protected\ControlProcessWindow.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i69">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\protected\ObjectAttributes.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i70">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\protected\Process.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i71">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\protected\Process.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i72">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\protected\ProcessRepository.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i73">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\protected\StartProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i74">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\protected\StopProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i75">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\Save Chart.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i76">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\Set Graph Decimation.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i77">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\Set Graph Samples.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i78">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\Set High Speed.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i79">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\Set Pause.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i80">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\Set Time Selector.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i81">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\utils\Grapher_GetAttributes.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i82">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\utils\Grapher_New.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i83">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Acknowledge Faults.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i84">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Clear Reservation.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i85">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Configuration.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i86">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Connect.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i87">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Create.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i88">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Destroy.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i89">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Disconnect.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i90">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\ERROR_GLOBAL.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i91">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Get Capabilities.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i92">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Get Energize Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i93">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Get Faults.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i94">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Get Library Info.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i95">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Get Limits.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i96">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Get Measurements.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i97">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Get Mode.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i98">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Get Output Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i99">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Get Range.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i100">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Get Setpoints.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i101">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Get Slew Rates.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i102">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\HPS-17000-PowerModule.lvclass</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i103">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Identify.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i104">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Load Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i105">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Mode.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i106">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\private\Get HPS Fault Code Description.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i107">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\private\Get HPS Fault Code Info.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i108">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\private\Get MB Registers.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i109">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\private\Get XC Report.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i110">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\private\Search HPS Network.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i111">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\private\Send Connected Event.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i112">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\private\Send Disconnected Event.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i113">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\private\Update Setpoint.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i114">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\protected\ObjectAttributes.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i115">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\protected\Process.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i116">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\protected\Process.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i117">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\protected\ProcessRepository.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i118">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\protected\StartProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i119">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\protected\StopProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i120">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Range.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i121">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Register Events.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i122">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Reserve.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i123">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Search HPS Network.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i124">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Set Current.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i125">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Set Energize Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i126">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Set Limits.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i127">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Set Mode.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i128">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Set Output Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i129">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Set Range.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i130">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Set Resistance.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i131">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Set Slew Rates.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i132">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Set Voltage.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i133">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Start Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i134">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Stop Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i135">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\Unreserve.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i136">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\utils\HPS-17000-PowerModule_GetAttributes.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i137">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\utils\HPS-17000-PowerModule_New.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i138">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\Close Log.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i139">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\Create Log.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i140">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\Destroy.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i141">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\Logger.lvclass</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i142">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\Logger_Create.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i143">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\private</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i144">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\protected\ObjectAttributes.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i145">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\protected\Process.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i146">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\protected\Process.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i147">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\protected\ProcessRepository.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i148">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\protected\StartProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i149">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\protected\StopProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i150">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\Start Log.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i151">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\Stop Log.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i152">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\Update Log Directory.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i153">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\utils\Logger_GetAttributes.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i154">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\utils\Logger_New.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i155">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Acknowledge Faults.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i156">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Clear Reservation.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i157">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Connect.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i158">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Create.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i159">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Destroy.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i160">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Disconnect.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i161">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get Capabilities.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i162">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get Energize Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i163">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get Faults.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i164">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get Library Info.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i165">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get Limits.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i166">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get Measurements.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i167">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get Mode.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i168">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get Output Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i169">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get PPL Info.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i170">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get Range.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i171">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get Setpoints.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i172">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Get Slew Rates.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i173">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Identify.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i174">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Limits.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i175">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Load Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i176">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Measurements.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i177">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\PowerModuleInterface.lvclass</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i178">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Range.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i179">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Reserve.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i180">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Set Current.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i181">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Set Energize Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i182">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Set Limits.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i183">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Set Mode.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i184">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Set Output Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i185">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Set Range.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i186">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Set Resistance.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i187">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Set Slew Rates.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i188">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Set Voltage.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i189">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Slew Rates.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i190">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Start Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i191">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Stop Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i192">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface\Unreserve.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i193">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Script_class\private</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i194">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Script_class\protected</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i195">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Script_class\utils</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i196">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Acknowledge Faults.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i197">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Clear Reservation.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i198">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Configuration.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i199">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Connect.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i200">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Create.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i201">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Destroy.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i202">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Disconnect.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i203">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Get Capabilities.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i204">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Get Energize Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i205">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Get Faults.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i206">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Get Library Info.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i207">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Get Limits.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i208">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Get Measurements.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i209">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Get Mode.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i210">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Get Output Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i211">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Get Range.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i212">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Get Setpoints.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i213">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Get Slew Rates.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i214">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Identify.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i215">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Load Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i216">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Mode.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i217">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\private\Update Setpoint.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i218">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\protected\ObjectAttributes.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i219">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\protected\Process.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i220">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\protected\Process.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i221">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\protected\ProcessRepository.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i222">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\protected\StartProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i223">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\protected\StopProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i224">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Range.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i225">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Reserve.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i226">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Set Current.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i227">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Set Energize Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i228">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Set Limits.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i229">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Set Mode.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i230">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Set Output Enable.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i231">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Set Range.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i232">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Set Resistance.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i233">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Set Slew Rates.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i234">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Set Voltage.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i235">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Simulated-PowerModule.lvclass</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i236">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Start Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i237">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Stop Profile.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i238">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\Unreserve.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i239">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\utils\Simulated-PowerModule_GetAttributes.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i240">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\utils\Simulated-PowerModule_New.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i241">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\Destroy.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i242">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\private\Update Script Listbox.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i243">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\protected\ObjectAttributes.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i244">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\protected\Process.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i245">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\protected\Process.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i246">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\protected\ProcessRepository.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i247">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\protected\StartProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i248">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\protected\StopProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i249">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\SSH.lvclass</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i250">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\SSH_Create.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i251">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\utils\SSH_GetAttributes.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i252">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\utils\SSH_New.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i253">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Streamer_class\private</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i254">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Streamer_class\protected</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i255">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Streamer_class\utils</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i256">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\protected\ObjectAttributes.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i257">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\protected\Process.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i258">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\protected\Process.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i259">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\protected\ProcessRepository.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i260">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\protected\StartProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i261">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\protected\StopProcess.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i262">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\protected\VCS_GetInstance.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i263">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\utils\VCS_GetAttributes.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i264">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\utils\VCS_New.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i265">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\VCS.lvclass</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i266">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\VCS_CleanUp.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i267">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\VCS_Init.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i268">
            <PluginConfigurationOptions />
            <RelativePath>HPS-17000-PowerModule.lvlib</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i269">
            <PluginConfigurationOptions />
            <RelativePath>HPS17K Panel.lvlps</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i270">
            <PluginConfigurationOptions />
            <RelativePath>log-Volta Control Suite.txt</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i271">
            <PluginConfigurationOptions />
            <RelativePath>Main HMI.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i272">
            <PluginConfigurationOptions />
            <RelativePath>NHR-9300-PowerModule.lvlib</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i273">
            <PluginConfigurationOptions />
            <RelativePath>Power Modules (Linux RT).aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i274">
            <PluginConfigurationOptions />
            <RelativePath>Power Modules (Linux RT).lvlps</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i275">
            <PluginConfigurationOptions />
            <RelativePath>Power Modules (Linux RT).lvproj</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i276">
            <PluginConfigurationOptions />
            <RelativePath>Power Modules (Windows).aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i277">
            <PluginConfigurationOptions />
            <RelativePath>Power Modules (Windows).lvlps</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i278">
            <PluginConfigurationOptions />
            <RelativePath>Power Modules (Windows).lvproj</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i279">
            <PluginConfigurationOptions />
            <RelativePath>Power Modules.lvlps</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i280">
            <PluginConfigurationOptions />
            <RelativePath>PowerModuleInterface.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i281">
            <PluginConfigurationOptions />
            <RelativePath>PowerModuleInterface.lvlib</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i282">
            <PluginConfigurationOptions />
            <RelativePath>PowerModuleInterface.lvlps</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i283">
            <PluginConfigurationOptions />
            <RelativePath>PowerModuleInterface.lvproj</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i284">
            <PluginConfigurationOptions />
            <RelativePath>Python\hps17k_panel.egg-info\dependency_links.txt</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i285">
            <PluginConfigurationOptions />
            <RelativePath>Python\hps17k_panel.egg-info\PKG-INFO</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i286">
            <PluginConfigurationOptions />
            <RelativePath>Python\hps17k_panel.egg-info\requires.txt</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i287">
            <PluginConfigurationOptions />
            <RelativePath>Python\hps17k_panel.egg-info\SOURCES.txt</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i288">
            <PluginConfigurationOptions />
            <RelativePath>Python\hps17k_panel.egg-info\top_level.txt</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i289">
            <PluginConfigurationOptions />
            <RelativePath>Python\hps17k-pybamm-wrapper.py</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i290">
            <PluginConfigurationOptions />
            <RelativePath>Python\pyproject.toml</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i291">
            <PluginConfigurationOptions />
            <RelativePath>Simulated-PowerModule.lvlib</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i292">
            <PluginConfigurationOptions />
            <RelativePath>SubVIs\Dialog Launcher.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i293">
            <PluginConfigurationOptions />
            <RelativePath>SubVIs\Dialog Window.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i294">
            <PluginConfigurationOptions />
            <RelativePath>SubVIs\Get Timestamp String.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i295">
            <PluginConfigurationOptions />
            <RelativePath>SubVIs\HMI Test.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i296">
            <PluginConfigurationOptions />
            <RelativePath>SubVIs\Load PPL Versions.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i297">
            <PluginConfigurationOptions />
            <RelativePath>SubVIs\PPL Version Pre-Build Action.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i298">
            <PluginConfigurationOptions />
            <RelativePath>SubVIs\Queue Periodic Updates.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i299">
            <PluginConfigurationOptions />
            <RelativePath>SubVIs\Update Function UI.vi</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i300">
            <PluginConfigurationOptions />
            <RelativePath>Support Files\Install-PuTTY.bat</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i301">
            <PluginConfigurationOptions />
            <RelativePath>Support Files\LICENSE.rtf</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i302">
            <PluginConfigurationOptions />
            <RelativePath>Support Files\profile-example.csv</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i303">
            <PluginConfigurationOptions />
            <RelativePath>Support Files\profile-template.csv</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i304">
            <PluginConfigurationOptions />
            <RelativePath>Support Files\volta-icon.ico</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i305">
            <PluginConfigurationOptions />
            <RelativePath>Support Files\volta-icon.png</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i306">
            <PluginConfigurationOptions />
            <RelativePath>Types\Indicators.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i307">
            <PluginConfigurationOptions />
            <RelativePath>Types\Power Function.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i308">
            <PluginConfigurationOptions />
            <RelativePath>Types\Range.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i309">
            <PluginConfigurationOptions />
            <RelativePath>Types\Setpoints.ctl</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i310">
            <PluginConfigurationOptions />
            <RelativePath>Volta Control Suite (Linux RT).aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i311">
            <PluginConfigurationOptions />
            <RelativePath>Volta Control Suite (Linux RT).lvlps</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i312">
            <PluginConfigurationOptions />
            <RelativePath>Volta Control Suite (Linux RT).lvproj</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i313">
            <PluginConfigurationOptions />
            <RelativePath>Volta Control Suite (Windows).aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i314">
            <PluginConfigurationOptions />
            <RelativePath>Volta Control Suite (Windows).lvlps</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i315">
            <PluginConfigurationOptions />
            <RelativePath>Volta Control Suite (Windows).lvproj</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i316">
            <PluginConfigurationOptions />
            <RelativePath>Volta Control Suite.pbs</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i317">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\private</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i30" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i318">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\private</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i67" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i319">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\private</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i217" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i320">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\private</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i242" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i321">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\utils</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i18" />
                <SourceItem z:Ref="i19" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i322">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\utils</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i42" />
                <SourceItem z:Ref="i43" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i323">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\utils</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i60" />
                <SourceItem z:Ref="i61" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i324">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\utils</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i81" />
                <SourceItem z:Ref="i82" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i325">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\utils</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i136" />
                <SourceItem z:Ref="i137" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i326">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\utils</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i153" />
                <SourceItem z:Ref="i154" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i327">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\utils</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i239" />
                <SourceItem z:Ref="i240" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i328">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\utils</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i251" />
                <SourceItem z:Ref="i252" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i329">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\utils</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i263" />
                <SourceItem z:Ref="i264" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i330">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\private</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i8" />
                <SourceItem z:Ref="i9" />
                <SourceItem z:Ref="i10" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i331">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\private</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i50" />
                <SourceItem z:Ref="i51" />
                <SourceItem z:Ref="i52" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i332">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Script_class</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i193" />
                <SourceItem z:Ref="i194" />
                <SourceItem z:Ref="i195" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i333">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Streamer_class</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i253" />
                <SourceItem z:Ref="i254" />
                <SourceItem z:Ref="i255" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i334">
            <PluginConfigurationOptions />
            <RelativePath>Types</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i306" />
                <SourceItem z:Ref="i307" />
                <SourceItem z:Ref="i308" />
                <SourceItem z:Ref="i309" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i335">
            <PluginConfigurationOptions />
            <RelativePath>Python\hps17k_panel.egg-info</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i284" />
                <SourceItem z:Ref="i285" />
                <SourceItem z:Ref="i286" />
                <SourceItem z:Ref="i287" />
                <SourceItem z:Ref="i288" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i336">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class\protected</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i11" />
                <SourceItem z:Ref="i12" />
                <SourceItem z:Ref="i13" />
                <SourceItem z:Ref="i14" />
                <SourceItem z:Ref="i15" />
                <SourceItem z:Ref="i16" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i337">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class\protected</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i53" />
                <SourceItem z:Ref="i54" />
                <SourceItem z:Ref="i55" />
                <SourceItem z:Ref="i56" />
                <SourceItem z:Ref="i57" />
                <SourceItem z:Ref="i58" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i338">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\protected</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i114" />
                <SourceItem z:Ref="i115" />
                <SourceItem z:Ref="i116" />
                <SourceItem z:Ref="i117" />
                <SourceItem z:Ref="i118" />
                <SourceItem z:Ref="i119" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i339">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class\protected</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i144" />
                <SourceItem z:Ref="i145" />
                <SourceItem z:Ref="i146" />
                <SourceItem z:Ref="i147" />
                <SourceItem z:Ref="i148" />
                <SourceItem z:Ref="i149" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i340">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class\protected</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i218" />
                <SourceItem z:Ref="i219" />
                <SourceItem z:Ref="i220" />
                <SourceItem z:Ref="i221" />
                <SourceItem z:Ref="i222" />
                <SourceItem z:Ref="i223" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i341">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class\protected</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i243" />
                <SourceItem z:Ref="i244" />
                <SourceItem z:Ref="i245" />
                <SourceItem z:Ref="i246" />
                <SourceItem z:Ref="i247" />
                <SourceItem z:Ref="i248" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i342">
            <PluginConfigurationOptions />
            <RelativePath>Support Files</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i300" />
                <SourceItem z:Ref="i301" />
                <SourceItem z:Ref="i302" />
                <SourceItem z:Ref="i303" />
                <SourceItem z:Ref="i304" />
                <SourceItem z:Ref="i305" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i343">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class\protected</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i68" />
                <SourceItem z:Ref="i69" />
                <SourceItem z:Ref="i70" />
                <SourceItem z:Ref="i71" />
                <SourceItem z:Ref="i72" />
                <SourceItem z:Ref="i73" />
                <SourceItem z:Ref="i74" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i344">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class\protected</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i256" />
                <SourceItem z:Ref="i257" />
                <SourceItem z:Ref="i258" />
                <SourceItem z:Ref="i259" />
                <SourceItem z:Ref="i260" />
                <SourceItem z:Ref="i261" />
                <SourceItem z:Ref="i262" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i345">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class\protected</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i31" />
                <SourceItem z:Ref="i32" />
                <SourceItem z:Ref="i33" />
                <SourceItem z:Ref="i34" />
                <SourceItem z:Ref="i35" />
                <SourceItem z:Ref="i36" />
                <SourceItem z:Ref="i37" />
                <SourceItem z:Ref="i38" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i346">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class\private</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i106" />
                <SourceItem z:Ref="i107" />
                <SourceItem z:Ref="i108" />
                <SourceItem z:Ref="i109" />
                <SourceItem z:Ref="i110" />
                <SourceItem z:Ref="i111" />
                <SourceItem z:Ref="i112" />
                <SourceItem z:Ref="i113" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i347">
            <PluginConfigurationOptions />
            <RelativePath>SubVIs</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i292" />
                <SourceItem z:Ref="i293" />
                <SourceItem z:Ref="i294" />
                <SourceItem z:Ref="i295" />
                <SourceItem z:Ref="i296" />
                <SourceItem z:Ref="i297" />
                <SourceItem z:Ref="i298" />
                <SourceItem z:Ref="i299" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i348">
            <PluginConfigurationOptions />
            <RelativePath>Classes\PowerModule_interface</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i155" />
                <SourceItem z:Ref="i156" />
                <SourceItem z:Ref="i157" />
                <SourceItem z:Ref="i158" />
                <SourceItem z:Ref="i159" />
                <SourceItem z:Ref="i160" />
                <SourceItem z:Ref="i161" />
                <SourceItem z:Ref="i162" />
                <SourceItem z:Ref="i163" />
                <SourceItem z:Ref="i164" />
                <SourceItem z:Ref="i165" />
                <SourceItem z:Ref="i166" />
                <SourceItem z:Ref="i167" />
                <SourceItem z:Ref="i168" />
                <SourceItem z:Ref="i169" />
                <SourceItem z:Ref="i170" />
                <SourceItem z:Ref="i171" />
                <SourceItem z:Ref="i172" />
                <SourceItem z:Ref="i173" />
                <SourceItem z:Ref="i174" />
                <SourceItem z:Ref="i175" />
                <SourceItem z:Ref="i176" />
                <SourceItem z:Ref="i177" />
                <SourceItem z:Ref="i178" />
                <SourceItem z:Ref="i179" />
                <SourceItem z:Ref="i180" />
                <SourceItem z:Ref="i181" />
                <SourceItem z:Ref="i182" />
                <SourceItem z:Ref="i183" />
                <SourceItem z:Ref="i184" />
                <SourceItem z:Ref="i185" />
                <SourceItem z:Ref="i186" />
                <SourceItem z:Ref="i187" />
                <SourceItem z:Ref="i188" />
                <SourceItem z:Ref="i189" />
                <SourceItem z:Ref="i190" />
                <SourceItem z:Ref="i191" />
                <SourceItem z:Ref="i192" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i349">
            <PluginConfigurationOptions />
            <RelativePath>Python</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i289" />
                <SourceItem z:Ref="i290" />
                <SourceItem z:Ref="i335" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i350">
            <PluginConfigurationOptions />
            <RelativePath>Classes\VCS_class</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i265" />
                <SourceItem z:Ref="i266" />
                <SourceItem z:Ref="i267" />
                <SourceItem z:Ref="i344" />
                <SourceItem z:Ref="i329" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i351">
            <PluginConfigurationOptions />
            <RelativePath>Classes\SSH_class</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i241" />
                <SourceItem z:Ref="i249" />
                <SourceItem z:Ref="i250" />
                <SourceItem z:Ref="i320" />
                <SourceItem z:Ref="i341" />
                <SourceItem z:Ref="i328" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i352">
            <PluginConfigurationOptions />
            <RelativePath>Classes\ACIR_EIS_class</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i2" />
                <SourceItem z:Ref="i3" />
                <SourceItem z:Ref="i4" />
                <SourceItem z:Ref="i5" />
                <SourceItem z:Ref="i6" />
                <SourceItem z:Ref="i7" />
                <SourceItem z:Ref="i17" />
                <SourceItem z:Ref="i330" />
                <SourceItem z:Ref="i336" />
                <SourceItem z:Ref="i321" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i353">
            <PluginConfigurationOptions />
            <RelativePath>Classes\DCIR_HPPC_class</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i44" />
                <SourceItem z:Ref="i45" />
                <SourceItem z:Ref="i46" />
                <SourceItem z:Ref="i47" />
                <SourceItem z:Ref="i48" />
                <SourceItem z:Ref="i49" />
                <SourceItem z:Ref="i59" />
                <SourceItem z:Ref="i331" />
                <SourceItem z:Ref="i337" />
                <SourceItem z:Ref="i323" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i354">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Logger_class</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i138" />
                <SourceItem z:Ref="i139" />
                <SourceItem z:Ref="i140" />
                <SourceItem z:Ref="i141" />
                <SourceItem z:Ref="i142" />
                <SourceItem z:Ref="i150" />
                <SourceItem z:Ref="i151" />
                <SourceItem z:Ref="i152" />
                <SourceItem z:Ref="i143" />
                <SourceItem z:Ref="i339" />
                <SourceItem z:Ref="i326" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i355">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Grapher_class</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i62" />
                <SourceItem z:Ref="i63" />
                <SourceItem z:Ref="i64" />
                <SourceItem z:Ref="i65" />
                <SourceItem z:Ref="i66" />
                <SourceItem z:Ref="i75" />
                <SourceItem z:Ref="i76" />
                <SourceItem z:Ref="i77" />
                <SourceItem z:Ref="i78" />
                <SourceItem z:Ref="i79" />
                <SourceItem z:Ref="i80" />
                <SourceItem z:Ref="i318" />
                <SourceItem z:Ref="i343" />
                <SourceItem z:Ref="i324" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i356">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Battery_class</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i20" />
                <SourceItem z:Ref="i21" />
                <SourceItem z:Ref="i22" />
                <SourceItem z:Ref="i23" />
                <SourceItem z:Ref="i24" />
                <SourceItem z:Ref="i25" />
                <SourceItem z:Ref="i26" />
                <SourceItem z:Ref="i27" />
                <SourceItem z:Ref="i28" />
                <SourceItem z:Ref="i29" />
                <SourceItem z:Ref="i39" />
                <SourceItem z:Ref="i40" />
                <SourceItem z:Ref="i41" />
                <SourceItem z:Ref="i317" />
                <SourceItem z:Ref="i345" />
                <SourceItem z:Ref="i322" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i357">
            <PluginConfigurationOptions />
            <RelativePath>Classes\Simulated-PowerModule_class</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i196" />
                <SourceItem z:Ref="i197" />
                <SourceItem z:Ref="i198" />
                <SourceItem z:Ref="i199" />
                <SourceItem z:Ref="i200" />
                <SourceItem z:Ref="i201" />
                <SourceItem z:Ref="i202" />
                <SourceItem z:Ref="i203" />
                <SourceItem z:Ref="i204" />
                <SourceItem z:Ref="i205" />
                <SourceItem z:Ref="i206" />
                <SourceItem z:Ref="i207" />
                <SourceItem z:Ref="i208" />
                <SourceItem z:Ref="i209" />
                <SourceItem z:Ref="i210" />
                <SourceItem z:Ref="i211" />
                <SourceItem z:Ref="i212" />
                <SourceItem z:Ref="i213" />
                <SourceItem z:Ref="i214" />
                <SourceItem z:Ref="i215" />
                <SourceItem z:Ref="i216" />
                <SourceItem z:Ref="i224" />
                <SourceItem z:Ref="i225" />
                <SourceItem z:Ref="i226" />
                <SourceItem z:Ref="i227" />
                <SourceItem z:Ref="i228" />
                <SourceItem z:Ref="i229" />
                <SourceItem z:Ref="i230" />
                <SourceItem z:Ref="i231" />
                <SourceItem z:Ref="i232" />
                <SourceItem z:Ref="i233" />
                <SourceItem z:Ref="i234" />
                <SourceItem z:Ref="i235" />
                <SourceItem z:Ref="i236" />
                <SourceItem z:Ref="i237" />
                <SourceItem z:Ref="i238" />
                <SourceItem z:Ref="i319" />
                <SourceItem z:Ref="i340" />
                <SourceItem z:Ref="i327" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i358">
            <PluginConfigurationOptions />
            <RelativePath>Classes\HPS-17000_class</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i83" />
                <SourceItem z:Ref="i84" />
                <SourceItem z:Ref="i85" />
                <SourceItem z:Ref="i86" />
                <SourceItem z:Ref="i87" />
                <SourceItem z:Ref="i88" />
                <SourceItem z:Ref="i89" />
                <SourceItem z:Ref="i90" />
                <SourceItem z:Ref="i91" />
                <SourceItem z:Ref="i92" />
                <SourceItem z:Ref="i93" />
                <SourceItem z:Ref="i94" />
                <SourceItem z:Ref="i95" />
                <SourceItem z:Ref="i96" />
                <SourceItem z:Ref="i97" />
                <SourceItem z:Ref="i98" />
                <SourceItem z:Ref="i99" />
                <SourceItem z:Ref="i100" />
                <SourceItem z:Ref="i101" />
                <SourceItem z:Ref="i102" />
                <SourceItem z:Ref="i103" />
                <SourceItem z:Ref="i104" />
                <SourceItem z:Ref="i105" />
                <SourceItem z:Ref="i120" />
                <SourceItem z:Ref="i121" />
                <SourceItem z:Ref="i122" />
                <SourceItem z:Ref="i123" />
                <SourceItem z:Ref="i124" />
                <SourceItem z:Ref="i125" />
                <SourceItem z:Ref="i126" />
                <SourceItem z:Ref="i127" />
                <SourceItem z:Ref="i128" />
                <SourceItem z:Ref="i129" />
                <SourceItem z:Ref="i130" />
                <SourceItem z:Ref="i131" />
                <SourceItem z:Ref="i132" />
                <SourceItem z:Ref="i133" />
                <SourceItem z:Ref="i134" />
                <SourceItem z:Ref="i135" />
                <SourceItem z:Ref="i346" />
                <SourceItem z:Ref="i338" />
                <SourceItem z:Ref="i325" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i359">
            <PluginConfigurationOptions />
            <RelativePath>Classes</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i352" />
                <SourceItem z:Ref="i356" />
                <SourceItem z:Ref="i353" />
                <SourceItem z:Ref="i355" />
                <SourceItem z:Ref="i358" />
                <SourceItem z:Ref="i354" />
                <SourceItem z:Ref="i348" />
                <SourceItem z:Ref="i332" />
                <SourceItem z:Ref="i357" />
                <SourceItem z:Ref="i351" />
                <SourceItem z:Ref="i333" />
                <SourceItem z:Ref="i350" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i360">
            <PluginConfigurationOptions />
            <RelativePath>..\src</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i268" />
                <SourceItem z:Ref="i269" />
                <SourceItem z:Ref="i270" />
                <SourceItem z:Ref="i271" />
                <SourceItem z:Ref="i272" />
                <SourceItem z:Ref="i273" />
                <SourceItem z:Ref="i274" />
                <SourceItem z:Ref="i275" />
                <SourceItem z:Ref="i276" />
                <SourceItem z:Ref="i277" />
                <SourceItem z:Ref="i278" />
                <SourceItem z:Ref="i279" />
                <SourceItem z:Ref="i280" />
                <SourceItem z:Ref="i281" />
                <SourceItem z:Ref="i282" />
                <SourceItem z:Ref="i283" />
                <SourceItem z:Ref="i291" />
                <SourceItem z:Ref="i310" />
                <SourceItem z:Ref="i311" />
                <SourceItem z:Ref="i312" />
                <SourceItem z:Ref="i313" />
                <SourceItem z:Ref="i314" />
                <SourceItem z:Ref="i315" />
                <SourceItem z:Ref="i316" />
                <SourceItem z:Ref="i359" />
                <SourceItem z:Ref="i349" />
                <SourceItem z:Ref="i347" />
                <SourceItem z:Ref="i342" />
                <SourceItem z:Ref="i334" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
    </SourceItems>
    <InputSourceItems>
        <SourceItem z:Ref="i360" />
    </InputSourceItems>
    <Distributions>
        <Distribution z:Id="i361" i:type="Package">
            <DistributionItems />
            <Name>Volta Control Suite</Name>
            <OutputDirectory>Packages</OutputDirectory>
            <PluginConfigurationOptions />
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <Architecture>windows_x64</Architecture>
            <AutoIncrementVersion>Build</AutoIncrementVersion>
            <BuildStatus z:Id="i362">
                <FileName />
                <Version>none</Version>
            </BuildStatus>
            <CompanyName>MyCompany</CompanyName>
            <CustomExecutes />
            <DisplayName>Volta Control Suite</DisplayName>
            <FileName>mycompany-myproduct_1.0.0.0_windows_x64.nipkg</FileName>
            <MaintainerEmail>email@mycompany.com</MaintainerEmail>
            <MaintainerName>MyCompany</MaintainerName>
            <Messages xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
            <PackageName>mycompany-myproduct</PackageName>
            <PackageRelationships />
            <ProductName>MyProduct</ProductName>
            <Section>Application Software</Section>
            <Synopsis>mycompany-myproduct</Synopsis>
            <Version>1.0.0.0</Version>
        </Distribution>
    </Distributions>
    <Feeds />
    <DistributionGroups>
        <DistributionGroup z:Id="i363">
            <Distributions>
                <Distribution z:Ref="i361" />
            </Distributions>
            <Name>Distribution Group</Name>
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <StageDirectory>ProcessingStage</StageDirectory>
        </DistributionGroup>
    </DistributionGroups>
    <TestStandMode>true</TestStandMode>
    <PluginConfigurationOptions>
        <ConfigurationOption z:Id="i364">
            <Definition z:Id="i365">
                <Description i:nil="true" />
                <Name>TestStand Options</Name>
            </Definition>
            <HasDefaultValues>true</HasDefaultValues>
            <Value z:Id="i366" i:type="DialogConfigurationOptionValue">
                <Values>
                    <ConfigurationOptionValue z:Id="i367" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i368" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i369" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i370" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i371" i:type="StringConfigurationOptionValue">
                        <Value>SupportVIs</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i372" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i373" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i374" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i375" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i376" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i377" i:type="BooleanConfigurationOptionValue">
                        <Value>true</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i378" i:type="BooleanConfigurationOptionValue">
                        <Value>true</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i379" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i380" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i381" i:type="PathConfigurationOptionValue">
                        <RelativePath />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i382" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i383" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i384" i:type="StringConfigurationOptionValue">
                        <Value>[BootVolume]</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i385" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i386" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i387" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i388" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i389" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i390" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i391" i:type="BooleanConfigurationOptionValue" />
                </Values>
            </Value>
        </ConfigurationOption>
    </PluginConfigurationOptions>
</Solution>